#
###################################
# Site wide configuration
####################################
#
title: Ryan Zhang
email: tyzhang2014@gmail.com
description: A simple and awesome blog theme powered by jekyll.
url: https://zhan4139.github.io # the base hostname & protocol for your site
keywords: ["Programming", "Java", "JavaScript"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Los_Angeles
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Ryan
  avatar: profile.jpeg
  job: "Prospect Software Engineer"
  bio: "A graduate student, a full-stack enthusiast, a mobile development lover @Seattle, WA."
  email: tyzhang2014@gmail.com
  disqus-shortname: ryanblog
  twitter: zhan4139 #username
  facebook: ryan.t.zhang #username
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: zhan4139 #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: ryan-t-zhang #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
